version: '3.8'

services:
  kimi_voice_ai:
    container_name: kimi_voice_ai
    build:
      context: .
      dockerfile: Dockerfile
    runtime: nvidia
    environment:
      - TZ=Europe/Moscow
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    ports:
      - "5000:5000"  # FastAPI
      - "8888:8888"  # Jupyter
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]
#    command: ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--allow-root", "--no-browser"]
#    command: >
#      bash -c "jupyter notebook --ip=0.0.0.0 --port=8888 --allow-root --no-browser & uvicorn app:app --host 0.0.0.0 --port 5000 --reload"